cryptogarageinc/cfd-go

cfdgo.c, cfdgo.go, cfdgo_test.go, swig.i
- [#978](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/978)
- Go言語向けのParseScript APIを作成
- (cfd) その他のAPIと合わせてtypeを変更
- (cfd-go) Go言語I/Fとテストコード追加
```bash
npm run cmake_all
LD_LIBRARY_PATH=./build/Release/ go build
LD_LIBRARY_PATH=./build/Release/ go test
npm run check
```
- 
**PRを出した人**
**レビューする人**
swigのI/Fで、errorを返却するようにする修正は実装中
=> ParseScript APIのGo言語APIを作成

cfdgo.go
godocの軽微な修正のため無し
CfdGoCreateConfidentialSighash()のgodocの修正
コメントの修正のみのため、動作には影響しない
**PRを出した人**
**レビューする人**
=> CfdGoCreateConfidentialSighash()のgodoc修正

Dockerfile
- [#1020](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1020)
- cfd-go build用Dockerの作成/修正
- btclib-sandbox build用Dockerのgo binaryを利用するimageの作成
-> exampleのベースになれば...
```bash
cd wrap_go && docker-compose up
or
cd external/cfd-go && docker build -t cryptogarageinc/cfd-go .
cd ../../wrap_go && docker build -t cryptogarageinc/cfd-go-app .
```
- 
**PRを出した人**
**レビューする人**
- 修正として、クリーン環境からのビルドは `docker build --no-cache <...>`で実行してもらう前提として、内部処理はクリーンにしました。
- また、このDockerfile単体で利用するケースをどう表現すれば良いかわからなかったため、READMEには追記しておりません
- 何かアイディアがあれば...
=> Dockerファイル作成/修正 + 検証

.gitattributes, .github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml
- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1039
- 1039: CI追加
```bash
```
- 
**PRを出した人**
**レビューする人**
=> add ci setting.

local_resource/external_project_local_setting.config
- 依存ライブラリのversion変更漏れ
```bash
```
- 
**PRを出した人**
**レビューする人**
=> change submodule target version

cfdgo.c, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- [#1046](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1046)
- (cfd) DerEncodeのcapiを追加
- (cfd-go) Golang用 DerEncodeをExport
```bash
npm run check_all
```
- 
**PRを出した人**
**レビューする人**
=> DerEncode APIの追加

cfdgo.c, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- [#1035](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1035) 
- [#1036](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1036) 
- (cfd) Script構築C APIを作成
- ScriptはASMを文字列で受け取る
- (cfd-go) Script構築Go APIを作成
- Scriptは各要素を文字列で受け取る想定
- ASMからの変換も念のため追加
```bash
npm run check_all
```
- 
**PRを出した人**
**レビューする人**
=> Script自由構築APIを作成

README.md, cfdgo.c, cfdgo.go, cfdgo_test.go, swig.i
- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1060
- #1055 の cfd-go版
```bash
go test
```
- 
**PRを出した人**
**レビューする人**
実験的に、ハンドル未指定時の内部ハンドル確保対応を行っています。今後水平展開予定。
=> add CreateMultisigScriptSig API

README.md, cfdgo.go, swig.i
- なし（1分修正）
- READMEのnpm scriptの実行について、 `npm run <script>` の runが抜けていた問題の修正
何かを実行するわけではないので、目検での確認で大丈夫だと思います。
```bash
```
- 
**PRを出した人**
**レビューする人**
=> READMEのスクリプトサンプルの修正

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- [#1069](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1069)
- (cfd) capiのCfdGetDescriptorDataに `request signature num`を追加する
- (cfd-go) CfdDescriptorData の Struct に ReqSigNum を追加する様に修正
```bash
CI待ち
```
- ~~capiにテストコードがなかったので、テストは保留~~
- やりました
**PRを出した人**
**レビューする人**
=> Multisigのrequest signature num を CfdGetDescriptorData に追加

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/create_release-and-upload.yml, README.md, cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i, tools/gen_swig.bat, tools/gen_swig.sh
- update to sprint33
```bash
```
- 
**PRを出した人**
**レビューする人**
=> update to sprint33

cfdgo.cxx, cfdgo.go, cfdgo_test.go, swig.i
- [#1090](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1090)
- EstimateFeeのAPIをgo向けに追加
```bash
CI待ち
```
- 
**PRを出した人**
**レビューする人**
=> Go向けEstimateFeeのAPIを追加

README.md, tools/build_mingw.bat, tools/build_mingw_debug.bat, tools/cleanup_install_files.sh, tools/cmake_cleanup.bat, tools/cmake_cleanup.sh
- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1135
- cleanup scriptの追加
```bash
```
- 
**PRを出した人**
**レビューする人**
=> add cleanup script

README.md, external/CMakeLists.txt, local_resource/external_project_local_setting.config
- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1136
- git ssh接続対応
- 環境変数設定により、git ssh接続が行えるようにする。
```bash
```
- 
**PRを出した人**
**レビューする人**
=> support git-ssh connection

.travis.yml, local_resource/external_project_local_setting.config
- Update to sprint39
```bash
```
- 
**PRを出した人**
**レビューする人**
=> Update to sprint39

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- Update to sprint41
```bash
```
- 
**PRを出した人**
**レビューする人**
=> Update to sprint41

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- hotfix: Update to sprint43-preview
- for v0.0.17
```bash
```
- 
**PRを出した人**
**レビューする人**
=> Update to sprint43-preview

README.md
- README.mdの更新
- 開発関連情報を追記。
```bash
```
- 
**PRを出した人**
**レビューする人**
=> docs: add develop info on README.md.

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- update to v0.1.21
```bash
```
- 
**PRを出した人**
**レビューする人**
=> update to v0.1.21

local_resource/external_project_local_setting.config
- 
```bash
```
- 
**PRを出した人**
**レビューする人**
=> upgrade: update cfd-core version

cfdgo.cxx, cfdgo.go, swig.i
なし
- CfdGoEstimateFeeのコメント修正と処理の変更を伴わない軽微なリファクタリング
リファクタリングのため、なし
- なし
**PRを出した人**
**レビューする人**
- なし
=> refactor: CfdGoEstimateFee Light refactor

.github/workflows/create_release-and-upload.yml, cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- update to v0.1.27
- feat: add GetCommitment API
- feat: add windows releases asset
```bash
```
** Reviewer **
=> update to v0.1.27

local_resource/external_project_local_setting.config
- update to v0.1.28
- upgrade cfd version (fix blinding)
```bash
```
** Reviewer **
=> update to v0.1.28

cfdgo_test.go, local_resource/external_project_local_setting.config
- update to v0.1.30
- feat: parse miniscript on descriptor
```bash
```
** Reviewer **
=> update to v0.1.30

README.md
#80 
- document updated.
- add windows install. move releases asset.
```bash
```
** Reviewer **
=> doc: add windows install. move releases asset.

local_resource/external_project_local_setting.config
- fix: verifysign check lockingScript
- doc: add windows install. move releases asset.
```bash
```
** Reviewer **
=> update to v0.1.31

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, cfdgo.cxx, cfdgo.go, swig.i
- fix: target go version on CI
- add go 1.15
- fix: support go 1.15
- on linux and macos
```bash
```
** Reviewer **
=> fix: support go 1.15

cfdgo.cxx, cfdgo.go, cfdgo_test.go, go.mod, local_resource/external_project_local_setting.config, swig.i
- feat: update schnorr API (change I/F)
- feat: update go v1.14
```bash
```
** Reviewer **
=> update to v0.2.0

.github/workflows/create_release-and-upload.yml
- refactor: collect upload url
```bash
```
** Reviewer **
=> refactor: collect upload url

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- update cfd v0.2.6
- feat: add SchnorrPubkey API
- test: add code scan
```bash
```
** Reviewer **
=> update to v0.2.3

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- feat: add schnorr tweak API
```bash
```
** Reviewer **
=> feat: add schnorr tweak API

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- feat: add tweakadd schnorrPubkey API
- update cfd v0.2.7
```bash
```
** Reviewer **
=> update to v0.2.4

cfdgo.cxx, cfdgo.go, cfdgo_test.go, swig.i
- feat: output blinder
```bash
```
** Reviewer **
=> feat: output blinder

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/code_scanner.yml, README.md, go.mod
- test: upgrade testify
```bash
```
** Reviewer **
=> feat: upgrade go 1.16

cfdgo.cxx, cfdgo.go, cfdgo_test.go, swig.i
- fix: deprecated CfdEstimateFeeInput.
- feat: add new EstimateFee API.
```bash
```
** Reviewer **
=> fix: deprecated CfdEstimateFeeInput. add new EstimateFee API.

cfdgo_test.go
- test: add taproot address/fee test
```bash
```
** Reviewer **
=> test: add taproot address/fee test

.github/workflows/create_release-and-upload.yml, README.md, local_resource/external_project_local_setting.config
- doc: update README.md
- upgrade: update cfd version
- feat: add xcode asset version 
```bash
```
** Reviewer **
=> doc: update README.md

cfdgo.cxx, cfdgo.go, local_resource/external_project_local_setting.config, swig.i
- fix: rename roothash to basehash
```bash
```
** Reviewer **
=> fix: rename roothash to basehash

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i, tools/simple_build.sh
- feat: support taproot descriptor
- feat: add descriptor response root data
- chore: add linux/mac C++ simple build script. 
```bash
```
** Reviewer **
=> feat: taproot descriptor

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/create_release-and-upload.yml
- test: update ci on v0.1.x
```bash
```
** Reviewer **
=> test: update ci on v0.1.x

cfdgo.cxx, cfdgo.go, cfdgo_test.go, local_resource/external_project_local_setting.config, swig.i
- feat: refactor ECDSA adaptor (by secp256k1-zkp)
```bash
```
** Reviewer **
=> feat: refactor ECDSA adaptor (by secp256k1-zkp)

cfdgo.cxx, cfdgo.go, cfdgo_tests_elements_test.go, local_resource/external_project_local_setting.config, swig.i
- feat: add pegout address API
```bash
```
** Reviewer **
=> feat: add pegout address API

apis/key/hdwallet.go, apis/key/hdwallet_test.go, apis/key/key.go, apis/key/key_test.go, cfdgo_api.go, cfdgo_test.go, local_resource/external_project_local_setting.config, types/ext_pubkey.go, types/extkey_type.go
- upgrade: update cfd, cfd-core, libwally-core 
- feat: add CfdGoGetExtkeyInfo
- feat: add apis/key API & test. add types.
```bash
```
** Reviewer **
=> feat: update to v0.3.7

local_resource/external_project_local_setting.config
- upgrade: update cfd
```bash
```
** Reviewer **
=> Update to v0.3.8

.github/workflows/check_pre-merge_master.yml, apis/descriptor/descriptor.go, apis/transaction/elements_tx.go, apis/transaction/elements_tx_test.go, apis/transaction/transaction.go, cfdgo.cxx, cfdgo.go, cfdgo_api.go, cfdgo_test.go, cfdgo_tests_elements_test.go, local_resource/external_project_local_setting.config, service/pegin/pegin.go, service/pegin/pegin_test.go, types/confidential_transaction.go, types/descriptor.go, types/transaction.go
- fix: support txoutproof size on pegin
- fix: calculate dummy txout fee.
- fix: taproot output descriptor
- fix: single key taproot
```bash
```
** Reviewer **
=> fix: support txoutproof size on pegin

cfdgo_test.go
- test: add taproot key-tree
```bash
```
** Reviewer **
=> test: add taproot key-tree

cfdgo.cxx, cfdgo.go, swig.i
- fix: remove include for sandbox
```bash
```
** Reviewer **
=> fix: remove include for sandbox

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/create_release-and-upload.yml, apis/transaction/elements_tx.go, apis/transaction/elements_tx_test.go, cfdgo_api.go, types/address_type.go, types/extkey_type.go, types/hash_type.go, types/network_type.go, types/sighash_type.go
- feat: blind opt nil
- feat: add String API
- feat: add unblind API
- test: update go version on CI 
```bash
```
** Reviewer **
=> feat: update to v0.3.12

.github/workflows/docker/alpine_build_entrypoint.sh, apis/descriptor/descriptor.go, apis/descriptor/descriptor_test.go, apis/transaction/elements_tx.go, apis/transaction/elements_tx_test.go, errors/error.go, types/confidential_transaction.go, types/descriptor.go, types/hash_type.go, types/sign_parameter.go
- feat: add parse descriptor by filter API 
- feat: add verify signature API
- feat: add types API
- fix: change ls command on release CI
```bash
```
** Reviewer **
=> feat: update to v0.3.13

apis/descriptor/descriptor_test.go, apis/factory_test.go, apis/key/key.go, apis/key/mock/key.go, apis/transaction/elements_tx.go, apis/transaction/elements_tx_test.go, apis/transaction/mock/elements_tx.go, service/pegin/mock/pegin.go, service/pegin/pegin.go, service/pegin/pegin_test.go, service/pegout/mock/pegout.go, service/pegout/pegout.go, service/pegout/pegout_test.go, types/confidential_transaction.go
- feat: add subtractFee. 
- fix: utxo interface
- refactor: use pointer
- feat: add key api
```bash
```
- subtractFee指定時のFee計算で不具合がありそう。多分0-amount指定ケースで以前修正した箇所以外に不具合がある模様。
- 動作はするので、一旦これで行く。
** Reviewer **
=> feat: add subtractFee option

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, apis/transaction/elements_tx.go, apis/transaction/elements_tx_test.go, apis/transaction/mock/elements_tx.go, cfdgo.cxx, cfdgo.go, cfdgo_api.go, local_resource/external_project_local_setting.config, service/pegout/pegout.go, service/pegout/pegout_test.go, types/confidential_transaction.go
- feat: add unblind api
- feat: support golang 1.17
- fix: update mnemonic API
- test: update CI for golang 1.17 
- fix: pegout fund
```bash
```
** Reviewer **
=> update to v0.3.16

apis/key/hdwallet.go, apis/key/hdwallet_test.go, local_resource/external_project_local_setting.config, service/pegout/pegout_test.go
- feat: pegout segwit
- hotfix: support liquidv1 segwit pegout
- hotfix: convert from BIP84,BIP49 
```bash
```
** Reviewer **
=> feat: pegout segwit

apis/descriptor/descriptor.go, apis/descriptor/descriptor_test.go, apis/descriptor/mock/descriptor.go, apis/key/mock/hdwallet.go, apis/script/mock/script.go, apis/script/script.go, apis/script/script_test.go
- feat: add descriptor api
- feat: add script api
- fix: hdwallet mock
```bash
```
** Reviewer **
=> feat: add api, fix ScriptApi.AnalyzeLockingScript

.github/workflows/create_release-and-upload.yml, Makefile, apis/address/address.go, apis/address/confidential_address.go, apis/block/block.go, apis/crypto/crypto.go, apis/descriptor/descriptor.go, apis/key/hdwallet.go, apis/key/key.go, apis/script/script.go, apis/transaction/elements_tx.go, apis/transaction/ledger_liquid_lib.go, apis/transaction/transaction.go, service/pegin/pegin.go, service/pegout/pegout.go, types/privkey.go, types/pubkey.go, types/sighash_type.go, types/transaction.go
- feat: add define
- feat: add alpine 3.16 release asset
- feat: upgrade goimports
```bash
```
** Reviewer **
=> feat: add define, add alpine 3.16 release asset

local_resource/external_project_local_setting.config
- feat: support arm64v8 build
- update libwally-core
```bash
```
** Reviewer **
=> feat: support arm64v8 build

cfdgo.cxx, cfdgo.go, cfdgo_api.go, local_resource/external_project_local_setting.config
- fix: update CfdGoParseScript
- for arm64v8 test
```bash
```
** Reviewer **
=> fix: update CfdGoParseScript

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/code_scanner.yml, .github/workflows/create_release-and-upload.yml
- fix: update set-output to GITHUB_OUTPUT
- fix: codeql version
```bash
```
** Reviewer **
=> fix: update set output

.github/workflows/create_release-and-upload.yml
- fix: get version
```bash
```
** Reviewer **
=> fix: get version

.github/workflows/create_release-and-upload.yml
- fix: mingw release
```bash
```
** Reviewer **
=> fix: mingw release

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .golangci.yml, Makefile, apis/key/hdwallet.go, apis/key/key.go, apis/script/script.go, cfdgo_api.go, tests/json_address_test.go, tools/build_mingw.bat, tools/build_mingw_debug.bat
- feat: go 1.20 on CI
- feat: update formatter and linter
- test: add review-dog on CI
```bash
```
** Reviewer **
=> feat: go 1.20

.github/workflows/create_release-and-upload.yml
- remove ubuntu 18.04 and alpine 3.14
- update xcode version
- update github actions
```bash
```
** Reviewer **
=> feat: update ci 20230904

.github/workflows/check_pre-merge_develop.yml, .github/workflows/check_pre-merge_master.yml, .github/workflows/check_pre-merge_sprint.yml, .github/workflows/create_release-and-upload.yml, go.mod
- feat: update golang to 1.22
- feat: add alpine to 3.20 on CI
- fix: ignore macOS 13 and 14 on CI
- due to go test failure
```bash
```
** Reviewer **
=> feat: update go.mod and CI. ignore macOS over 13
